version: 0.2

  

phases:

  install:
    commands:
      # install required binary
      - wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
      - yum install unzip -y
      - unzip terraform_0.13.5_linux_amd64.zip
      - ./terraform init

  build:
    commands:
      - ./terraform plan
      - export AWS_ACCESS_KEY_ID="" 
      - export AWS_SECRET_ACCESS_KEY=""
      - ./terraform apply --auto-approve
      - ./terraform destroy --auto-approve

  
